services:
  app:
    container_name: app
    env_file: ".env"
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:latest
    container_name: db
    env_file: ".env"
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:

volumes:
  db_data:

